extends Node

var ngplus_flag: int = 0
var cur_day: int = 0
var cur_client: int = 1
var cur_stage: int = 0
var barscore: int = 0
var jillwallet: int = 0
var datestring: String = "TUE 13/12"
var dayphase: String = "room"
var ft_any: int = 0
var ft_alma: int = 0
var ft_stella: int = 0
var don: Array = ["", "", "", "", "", "", "", ""]
var dondrunk: Array = [0, 0, 0]
var ing: Array = ["", "", "", "", "", "", "", ""]
var ingdrunk: Array = [0, 0]
var sei: Array = ["", "", "", "", "", "", "", "", "", "", ""]
var seidrunk1: String = ""
var kim: Array = ["", "", "", "", ""]
var kimdrunk1: int = 0
var dorodrinks: Array = ["", "", "", "", "", "", "", "", "", "", "", "", "", ""]
var dorodrunk: Array = [0, 0]
var jamie: Array = ["", "", "", "", "", ""]
var miki: Array = ["", "", "", "", ""]
var drunkmiki1: int = 0
var alma: Array = ["", "", "", "", "", "", "", "", "", "", ""]
var almadrunk: Array = [0, 0]
var stel: Array = ["", "", "", "", "", "", "", "", "", "", "", ""]
var steldrunk1: int = 0
var art: Array = ["", "", "", "", "", "", ""]
var stream: Array = ["", "", "", "", "", ""]
var anna: String = ""
var streamdrunk1: int = 0
var db: Array = ["", "", "", "", "", "", "", ""]
var bettydrunk1: int = 0
var dana1: String = ""
var tay: Array = ["", ""]
var virgilio: Array = ["", "", "", "", "", "", "", "", ""]
var jill: Array = ["", ""]
var jilldrunk1: int = 0
var brian: Array = ["", ""]
var rad: Array = ["", ""]
var norma1: String = ""
var mario: Array = ["", "", "", "", ""]
var nacho: Array = ["", "", ""]
var lexi: Array = ["", ""]
var gabyorder: String = ""
var absinthe_add: int = 0
var rum_add: int = 0
var shop_tea: int = 0
var songs: Array = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
var shopitems: Array = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
var walls: Array = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
var tables: Array = [0, 0, 0, 1]
var wallstype: int = 0
var kotatsutype: int = 0
var porndl: int = 0
var lightdl: int = 0
var housedl: int = 0
var hopesshop: int = 0
var eltonsshop: int = 0
var havenshop: int = 0
var shootersong: int = 0
var barshop: int = 0
var endingshop: int = 0
var friendlyshop: int = 0
var gotmeshop: int = 0
var songnames: Array = ["", "", "", "", "", "", "", "", "", "", "", ""]
var mistakecounter: int = 0
var flawless_chain: int = 0
var shooterdone: int = 0
var framebar: int = 0
var wallpaperbar: int = 0
var streamingsong: int = 0
var mikisong: int = 0
var frontiersong: int = 0
var staffsong: int = 0
var ironheartsong: int = 0
var cashcounter: int = 0
var tipcounter: int = 0

func ResetAllVars():
	ngplus_flag = 0
	cur_day = 8
	cur_client = 5
	cur_stage = 1
	barscore = 0
	jillwallet = 0
	datestring = "TUE 13/12"
	dayphase = "room"
	ft_any = 0
	ft_alma = 0
	ft_stella = 0
	don = ["", "", "", "", "", "", "", ""]
	dondrunk = [0, 0, 0]
	ing = ["", "", "", "", "", "", "", ""]
	ingdrunk = [0, 0]
	sei = ["", "", "", "", "", "", "", "", "", "", ""]
	seidrunk1 = ""
	kim = ["", "", "", "", ""]
	kimdrunk1 = 0
	dorodrinks = ["", "", "", "", "", "", "", "", "", "", "", "", "", ""]
	dorodrunk = [0, 0]
	jamie = ["", "", "", "", "", ""]
	miki = ["", "", "", "", ""]
	drunkmiki1 = 0
	alma = ["", "", "", "", "", "", "", "", "", "", ""]
	almadrunk = [0, 0]
	stel = ["", "", "", "", "", "", "", "", "", "", "", ""]
	steldrunk1 = 0
	art = ["", "", "", "", "", "", ""]
	stream = ["", "", "", "", "", ""]
	streamdrunk1 = 0
	db = ["", "", "", "", "", "", "", ""]
	bettydrunk1 = 0
	dana1 = ""
	tay = ["", ""]
	virgilio = ["", "", "", "", "", "", "", "", ""]
	jill = ["", ""]
	jilldrunk1 = 0
	brian = ["", ""]
	rad = ["", ""]
	norma1 = ""
	mario = ["", "", "", "", ""]
	nacho = ["", "", ""]
	lexi = ["", ""]
	gabyorder = ""
	absinthe_add = 0
	rum_add = 0
	shop_tea = 0
	songs = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	shopitems = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	walls = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	tables = [0, 0, 0, 1]
	wallstype = 0
	kotatsutype = 0
	porndl = 0
	lightdl = 0
	housedl = 0
	hopesshop = 0
	eltonsshop = 0
	havenshop = 0
	shootersong = 0
	barshop = 0
	endingshop = 0
	friendlyshop = 0
	gotmeshop = 0
	songnames = ["", "", "", "", "", "", "", "", "", "", "", ""]
	mistakecounter = 0
	flawless_chain = 0
	shooterdone = 0
	framebar = 0
	wallpaperbar = 0
	streamingsong = 0
	mikisong = 0
	frontiersong = 0
	staffsong = 0
	ironheartsong = 0
	cashcounter = 0
	tipcounter = 0
